version: 2.1

defaults: &defaults
  docker:
    # To rebuild image, run from root of go_attack repo:
    # docker build --target=build-deps -t humancompatibleai/goattack:build-deps compose/cpp/
    # docker push humancompatibleai/goattack:build-deps
    - image: humancompatibleai/goattack:build-deps
      auth:
        username: $DOCKERHUB_USERNAME
        password: $DOCKERHUB_PASSWORD
  working_directory: /engines/KataGo-custom

executors:
  unit-test:
    <<: *defaults
    resource_class: xlarge

commands:
  dependencies:
    description: "Check out and compile"
    steps:
      - checkout

      - run:
          name: CMake
          command: cd cpp && cmake . -DUSE_BACKEND=CUDA -DUSE_TCMALLOC=1 -DNO_GIT_REVISION=1

      - run:
          name: make
          command: cd cpp && make clean && make -j

jobs:
  unit-test:
    executor: unit-test
    steps:
      - dependencies

      - run:
          name: Memory Monitor
          command: |
            mkdir /tmp/resource-usage
            export FILE=/tmp/resource-usage/memory.txt
            while true; do
              ps -u root eo pid,%cpu,%mem,args,uname --sort=-%mem >> $FILE
              echo "----------" >> $FILE
              sleep 1
            done
          background: true

      - run:
          name: katago runtests
          command: ./cpp/katago runtests

      - store_artifacts:
          path: /tmp/resource-usage
          destination: resource-usage

workflows:
  version: 2
  test:
    jobs:
      - unit-test:
          context:
          - docker-hub-creds
